# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true

python:
  - 2.7
  - 3.6

env:
  global:
    - CONDA_PACKAGES="scipy bcolz pytest future xarray dask scikit-image"
    - PIP_PACKAGES="tqdm codecov pytest-cov tqdm"
  matrix:
    - NUMPY="numpy" PANDAS="pandas"
    - NUMPY="numpy=1.12.1" PANDAS="pandas"
    - NUMPY="numpy" PANDAS="pandas=0.19.2"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $CONDA_PACKAGES $NUMPY $PANDAS
  - source activate test-environment
  - pip install $PIP_PACKAGES
  - pip install -e .

script:
  - py.test floater --cov=floater --cov-config .coveragerc --cov-report term-missing -v

after_success:
  - codecov
